apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ printf "data-%s-sc" (include "hpcc-azurefile.fullname" $) }}
provisioner: kubernetes.io/azure-file
mountOptions:
  - uid=10000 # uid of user 'hpcc'
  - gid=10001 # gid of group 'hpcc'
  - dir_mode=0700 # user read/write/execute
  - file_mode=0600 # user read/write
parameters:
  skuName: {{ .Values.dataStorage.sku | default "Standard_LRS" }}
reclaimPolicy: Retain
allowVolumeExpansion: true
