certificates:
  issuers:
    local:
      spec:
      # delete any alternative spec config, and then add vault
        ca: null
        selfSigned: null
        vault:
          server: http://vault.default:8200
          path: pki/sign/hpcclocal
          auth:
            kubernetes:
              mountPath: /v1/auth/kubernetes
              role: issuer
              secretRef:
                name: tbd # requires service account secret, set from command line
                key: token
    public:
      domain: myhpcc.com
      spec:
      # delete any alternative spec config, and then add vault
        ca: null
        selfSigned: null
        vault:
          server: http://vault.default:8200
          path: pki/sign/myhpcc-dot-com
          auth:
            kubernetes:
              mountPath: /v1/auth/kubernetes
              role: issuer
              secretRef:
                name: tbd # requires service account secret, set from command line
                key: token
