{{- $storage := (.Values.storage | default dict) -}}
{{- $dataStorage := ($storage.dataStorage | default dict) -}}
{{- if (and (not $dataStorage.existingClaim) (not $dataStorage.plane)) }}
{{ include "hpcc.addPVC" (dict "root" $ "name" "datastorage" "me" $dataStorage) }}
{{- end }}
