{{ range $.Values.eclagent -}}
{{- if not .disabled -}}
{{- $apptype := .type | default "hthor" -}} 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name | quote }}
spec:
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      run: {{ .name | quote }}
  template:
    metadata:
      labels:
        run: {{ .name | quote }}
    spec:
      serviceAccountName: hpcc
      initContainers:
        {{- include "hpcc.checkDataMount" (dict "root" $) | indent 6 }}
      containers:
      - name: {{ .name | quote }}
        workingDir: /var/lib/HPCCSystems
        command: [ agentexec ] 
        args: [ 
                {{ include "hpcc.configArg" . }},
                {{ include "hpcc.daliArg" $ }}
              ]
{{- include "hpcc.addSecurityContext" (dict "root" $ "me" .) | indent 8 }}
{{ include "hpcc.addImageAttrs" (dict "root" $ "me" .) | indent 8 }}
        volumeMounts:
{{ include "hpcc.addConfigMapVolumeMount" . | indent 8 }}
{{ include "hpcc.addDataVolumeMount" . | indent 8 }}
{{ include "hpcc.addDllVolumeMount" . | indent 8 }}
{{ include "hpcc.addSecretVolumeMounts" (dict "root" $ "categories" (list "all" "ecl" "storage" ) ) | indent 8 }}
      volumes:
{{ include "hpcc.addConfigMapVolume" . | indent 6 }}
{{ include "hpcc.addDataVolume" $ | indent 6 }}
{{ include "hpcc.addDllVolume" $ | indent 6 }}
{{ include "hpcc.addSecretVolumes" (dict "root" $ "categories" (list "all" "ecl" "storage" ) ) | indent 6 }}
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .name }}-configmap 
data:
  {{ .name }}.yaml: |
    version: 1.0
    eclagent:
{{ toYaml (omit . "logging") | indent 6 }}
{{- include "hpcc.generateLoggingConfig" (dict "root" $ "me" .) | indent 6 }}
    {{ $apptype }}:
{{ toYaml (omit . "logging") | indent 6 }}
{{- include "hpcc.generateLoggingConfig" (dict "root" $ "me" .) | indent 6 }}
    global:
{{ include "hpcc.generateGlobalConfigMap" $ | indent 6 }}
  {{ $apptype }}-jobspec.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: %jobname
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
          - name: %jobname
{{- include "hpcc.addSecurityContext" (dict "root" $ "me" .) | indent 12 }}
{{ include "hpcc.addImageAttrs" (dict "root" $ "me" .) | indent 12 }}
            resources:
              requests:
                #request-memory
                #request-cpu
              limits:
                #limit-memory
                #limit-cpu
            workingDir: /var/lib/HPCCSystems
            command: ["/bin/bash", "-c", "{{ $apptype }}  {{ include "hpcc.configArg.noquote" . }} {{ include "hpcc.daliArg.noquote" $ }} %args &&  curl -X POST http://localhost:15020/quitquitquit" ]
            volumeMounts:
{{ include "hpcc.addConfigMapVolumeMount" . | indent 12 }}
{{ include "hpcc.addDataVolumeMount" . | indent 12 }}
{{ include "hpcc.addDllVolumeMount" . | indent 12 }}
{{ include "hpcc.addSecretVolumeMounts" (dict "root" $ "categories" (list "all" "ecl" "storage" ) ) | indent 12 }}
          volumes:
{{ include "hpcc.addConfigMapVolume" . | indent 10 }}
{{ include "hpcc.addDataVolume" $ | indent 10 }}
{{ include "hpcc.addDllVolume" $ | indent 10 }}
{{ include "hpcc.addSecretVolumes" (dict "root" $ "categories" (list "all" "ecl" "storage" ) ) | indent 10 }}
          restartPolicy: Never
      backoffLimit: 0
      
---
{{- end }}
{{- end }}
