{{ range $.Values.eclccserver -}}
{{- if not .disabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name | quote }}
spec:
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      run: {{ .name | quote }}
  template:
    metadata:
      labels:
        run: {{ .name | quote }}
    spec:
      serviceAccountName: hpcc
      terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds | default 600 }}
      initContainers:
        {{- include "hpcc.checkDllMount" (dict "root" $) | indent 6 }}
        {{- include "hpcc.addBundles" (dict "root" $ "me" . "imagename" "eclccserver") | indent 6 }}
      containers:
      - name: {{ .name | quote }}
        workingDir: /var/lib/HPCCSystems
        command: [ eclccserver ] 
        args: [
                {{ include "hpcc.configArg" . }},
                {{ include "hpcc.daliArg" $ }}
              ]
{{- include "hpcc.addSecurityContext" (dict "root" $ "me" .) | indent 8 }}
{{ include "hpcc.addImageAttrs" (dict "root" $ "me" .) | indent 8 }}
        volumeMounts:
{{ include "hpcc.addConfigMapVolumeMount" . | indent 8 }}
{{ include "hpcc.addDataVolumeMount" . | indent 8 }}
{{ include "hpcc.addDllVolumeMount" . | indent 8 }}
{{ include "hpcc.addSecretVolumeMounts" (dict "root" $ "categories" (list "all" ) ) | indent 8 }}
        - name: "hpccbundles"
          mountPath: "/home/hpcc/.HPCCSystems"
      volumes:
{{ include "hpcc.addConfigMapVolume" . | indent 6 }}
{{ include "hpcc.addDataVolume" $ | indent 6 }}
{{ include "hpcc.addDllVolume" $ | indent 6 }}
{{ include "hpcc.addSecretVolumes" (dict "root" $ "categories" (list "all" ) ) | indent 6 }}
      - name: hpccbundles
        emptyDir: {}
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .name }}-configmap 
data:
  {{ .name }}.yaml: |
    version: 1.0
    eclccserver:
{{ toYaml (omit . "logging") | indent 6 }}
{{- include "hpcc.generateLoggingConfig" (dict "root" $ "me" .) | indent 6 }}
      queues:
{{ include "hpcc.generateConfigMapQueues" $ | indent 6 }}
    global:
{{ include "hpcc.generateGlobalConfigMap" $ | indent 6 }}
  compile-jobspec.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: %jobname
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
          - name: %jobname
{{- include "hpcc.addSecurityContext" (dict "root" $ "me" .) | indent 12 }}
{{ include "hpcc.addImageAttrs" (dict "root" $ "me" .) | indent 12 }}
            resources:
              requests:
                #request-memory
                #request-cpu
              limits:
                #limit-memory
                #limit-cpu
            workingDir: /var/lib/HPCCSystems
            command: ["/bin/bash", "-c", "eclccserver {{ include "hpcc.configArg.noquote" . }} {{ include "hpcc.daliArg.noquote" $ }} %args && curl -X POST http://localhost:15020/quitquitquit "]
            volumeMounts:
{{ include "hpcc.addConfigMapVolumeMount" . | indent 12 }}
{{ include "hpcc.addDataVolumeMount" . | indent 12 }}
{{ include "hpcc.addDllVolumeMount" . | indent 12 }}
{{ include "hpcc.addSecretVolumeMounts" (dict "root" $ "categories" (list "all" ) ) | indent 12 }}
          volumes:
{{ include "hpcc.addConfigMapVolume" . | indent 10 }}
{{ include "hpcc.addDataVolume" $ | indent 10 }}
{{ include "hpcc.addDllVolume" $ | indent 10 }}
{{ include "hpcc.addSecretVolumes" (dict "root" $ "categories" (list "all" ) ) | indent 10 }}
          restartPolicy: Never
      backoffLimit: 0
      
---
{{- end }}
{{- end }}
