{{- $serverName := (include "hpcc-nfs.fullname" $) }}
{{- range $plane := .Values.planes -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-%s-pv" $plane.name (include "hpcc-nfs.fullname" $) }}
  labels:
    store: {{ printf "%s-%s-pv" $plane.name (include "hpcc-nfs.fullname" $) }}
spec:
  capacity:
    storage: {{ $plane.size }}
  accessModes:
    - {{ $plane.rwmany | default false | ternary "ReadWriteMany" "ReadWriteOnce" }}
  nfs:
    server: {{ printf "%s.%s.svc.cluster.local" $serverName $.Values.namespace }}
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s-pvc" $plane.name (include "hpcc-nfs.fullname" $) }}
spec:
  accessModes:
    - {{ $plane.rwmany | default false | ternary "ReadWriteMany" "ReadWriteOnce" }}
  storageClassName: ""
  resources:
    requests:
      storage: {{ $plane.size }}
  selector:
    matchLabels:
      store: {{ printf "%s-%s-pv" $plane.name (include "hpcc-nfs.fullname" $) }}
---
{{ end }}
