# Default values for hpcc-nfs.
namespace: default

sharedStorage:
  size: 6Gi
  #existingClaim: myexistingclaim

# NB: the sum of the size's below should be <= the sharedStorage size

common:
  mountPrefix: "/var/lib/HPCCSystems"

planes:
- name: dali
  subPath: dalistorage
  size: 1Gi
  labels: [ "dali" ]
- name: dll
  subPath: queries # cannot currently be changed
  size: 1Gi
  labels: [ "dll" ]
  rwmany: true
- name: sasha
  subPath: sasha
  size: 1Gi
  rwmany: true
  labels: [ "sasha" ]
- name: data
  subPath: hpcc-data
  size: 3Gi
  labels: [ "data" ] # NB: all "data" planes will be auto mounted by engine components and others that require access to data
  rwmany: true
- name: mydropzone
  subPath: dropzone
  size: 1Gi
  rwmany: true
  labels: [ "lz" ]
