{{- range $plane := .Values.planes -}}
 {{- $num := int ( $plane.numDevices | default 1 ) -}}
 {{- range $elem := untilStep 1 (int (add $num 1)) 1 }}
  {{- $suffix := (eq $num 1) | ternary "" (printf "-many-%d" $elem) -}}
  {{- $deviceDir := (eq $num 1) | ternary "" (printf "/d%d" $elem) -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-%s-pv%s" $plane.name (include "hpcc-localfile.fullname" $) $suffix }}
  labels:
    store: {{ printf "%s-%s-pv%s" $plane.name (include "hpcc-localfile.fullname" $) $suffix }}
spec:
  storageClassName: "manual"
  capacity:
    storage: {{ $plane.size }}
  volumeMode: Filesystem
  accessModes:
    - {{ $plane.rwmany | default false | ternary "ReadWriteMany" "ReadWriteOnce" }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    type: Directory
    path: {{ printf "%s%s%s%s" $.Values.common.hostpath (regexMatch ".*/$" $.Values.common.hostpath | ternary "" "/") $plane.subPath $deviceDir | quote }}
---
 {{ end -}}
{{ end }}
