# Overrides for http-connect secrets in hpcc.
# NB: The "hpcc-connect-testsecret" should be created before installing the helm chart.

secrets:
  ecl:
    http-connect-basicsecret: "http-connect-basicsecret"
  eclUser:
    k8s-example: "k8s-example"
